config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  resources :welcome, only: [:show,:index]
  resources :team, only: [:index]
  resources :contact, only: [:index]
  resources :gossips
  resources :users
  resources :cities
  resources :sessions, only: [:new,:create,:destroy]
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  # validates :name, presence: true, uniqueness: true, format: { with: /[a-zA-Z ]*/, message: 'Please, enter a valid city' }
  # validates :zip_code, presence: true, format: { with: /[a-zA-Z0-9- ]*/, message: 'Please, enter a valid zipcode' }
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :gossip
  belongs_to :user
  # has_many :likes
  # has_many :users, through: :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  # validates :title, presence: { message: "%{value} Le titre doit contenir entre 3 et 14 caractères" }, length: { in: 3..14 }
  # validates :content, presence: { message: "Le contenu ne peut pas être vide" }
  belongs_to :user
  has_many :tag_of_gossips
  has_many :tags, through: :tag_of_gossips
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip, optional: true
  belongs_to :comment , optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_of_gossips
  has_many :gossips, through: :tag_of_gossips
end

app/models/tag_of_gossip.rb
class TagOfGossip < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/user.rb
class User < ApplicationRecord
  # validates :first_name, presence: true, length: { minimum: 2 }
  # validates :last_name, presence: true, length: { minimum: 2 }
  # validates :description, presence: true, length: { maximum: 150 }
  # validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+.)+[^@\s]+\z/, message: 'Please, enter a valid email address' }
  # validates :age, presence: true, numericality: { only_integer: true }
  # validates :password, presence: true, length: {in: 6..20}
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: 'PrivateMessage'
  has_many :received_messages, foreign_key: 'recipient_id', class_name: 'PrivateMessage'
  has_secure_password
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new]
  # before_action :authenticate_author, only: [:edit, :update, :destroy]

  def index
    @gossips = Gossip.all
  end

  def show
    @find_by_user_id = Gossip.find(params[:id]).user_id
    @find_by_city_id = User.find(Gossip.find(params[:id]).user_id).city_id
    @author = params[:id]
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new('title' => params[:title], 'content' => params[:content])
    @gossip.user = current_user

    if @gossip.save
      redirect_to welcome_path(session.id)

    else
      render new_gossip_path
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end 

  def update
    @gossip = Gossip.find(params[:id])

    if @gossip.update(post_params)
      redirect_to gossips_path
    else
      render :edit
    end
  end

  def destroy
   @gossip = Gossip.find(params[:id])
   @gossip.destroy
   redirect_to gossips_path
  end 
  
  private
    def post_params
      post_params = params.require(:gossip).permit(:title, :content)
    end

    def authenticate_user
      unless current_user
        flash[:danger] = "Please log in."
        redirect_to new_session_path
      end
    end

    # def authenticate_author
    #   unless current_user != @gossip.user(id)
    #     flash[:danger] = "Vous n'êtes pas l'auteur de cette publication, vous n'avez pas les droits."
    #     redirect_to new_session_path
    #   end
    # end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def create
    if User.create(post_params)
      redirect_to welcome_path(session.id)
    else
      render :new
    end
  end

  def update
    @gossip = Gossip.find(params[:id])

    if @gossip.update(post_params)
      redirect_to gossips_path
    else
      render :edit
    end
  end

  private

  def post_params
    post_params = params.require(:user).permit(:first_name, :last_name, :description, :email, :age, :password, :city_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/session_helper.rb
module SessionHelper
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossip/show.html.erb
<div class="card mb-3">
<div class="card-body">

<h6 class="card-subtitle mb-2">Gossip n° <%= params[:id].to_i %></h6>
<h5 class="card-title"> <%= Gossip.find(params[:id]).title %></h5>
<p class="card-text"><%= Gossip.find(params[:id]).content %></p>
<p><%= Gossip.find(params[:id]).created_at %></p>

<a href="#" class="badge badge-warning  ">Auteur : <a href="/author/<%= @find_by_user_id %>"><%= User.find(@find_by_user_id).first_name %></a><p>

app/views/gossips/edit.html.erb
<h1> Editer le potin </h1>

<% if @gossip.errors.any? %>
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @gossip do |f| %>
  <div class="form-group">
    <label> Title </label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
  <label> Contenu </label>
    <%= f.text_field :content, class: 'form-control' %>
  </div>
<div class="form-group">
<button type= "submit">Modifier le potin</button>
</div>
<% end %>

app/views/gossips/index.html.erb
<div class="container-raw">
  <% @gossips.each do |gossip, id| %>
<div class="cards-raw">
  <p class="title-raw">Gossip n°<%= gossip.id %></p>
  <p><strong>Titre</strong> : <%= gossip.title %></p>
  <p><strong>Auteur</strong> : <%= User.find(gossip.user_id).first_name %></p>
  <a href="/gossips/<%=gossip.id%>">Voir le potin</a>
    <%
=begin%>
 <a href="<%= gossip_path(gossip.id)%>" class="btn btn-danger" data-confirm= "sur?" data-method="DELETE">Supprimer</a> 
<%
=end%>
</div>
  <% end %>
</div>

app/views/gossips/new.html.erb
<h2 class="mb-3 h2-centered">Créez un gossip !</h2>
<div class="container-gossip-form">
  <div class="gossip-form">
  <%= form_tag url_for(action: 'create'), method: "post" do %>

    <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >

    <div class="form-group">
      <%= label_tag 'Titre' %>
      <%= text_field_tag 'title', @gossip.title, class: 'form-control', autofocus: true%>
      <small id="titleHelp" class="form-text text-muted">Entre 3 et 14 caractères.</small>
    </div>

    <div class="form-content">
        <%= label_tag 'Contenu' %>
        <%= text_area_tag 'content', @gossip.content, class: 'form-control', rows: 5 %>
    </div>

    <%= submit_tag "Publier", class: "button-gossip-form"%>
  <% end %>
  </div>
</div>

<div class='container'>
<% if @gossip.errors.any? %>
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/gossips/show.html.erb
<div class="container-raw">
  <div class="cards-raw">
    <h5 class="card-title text-center">Gossip n° <%= params[:id].to_i %></h5>
    <p><strong>Titre</strong> : <%= Gossip.find(params[:id]).title %></p>
    <p><%= Gossip.find(params[:id]).content %></p>
    <p><%= Gossip.find(params[:id]).created_at %></p>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"><strong>Auteur</strong> : <a href="/users/<%= @find_by_user_id %>"><%= User.find(@find_by_user_id).first_name %></a></li>
      <li class="list-group-item"><p><strong>Ville</strong> : <a href="/cities/<%= @find_by_city_id %>"><%= City.find(@find_by_city_id).name %></a><p></li>
    </ul>
    <div>
      <% if logged_in? %>
        <%= link_to "Editer ce potin", edit_gossip_path, class: 'btn btn-secondary' %>
        <%= link_to "Supprimer ce potin", gossip_path, method: :delete, class: 'btn btn-secondary' %>
        <%= link_to "Un petit commentaire ?", new_comment_path, class: 'btn btn-secondary ' %>
      <% else %>
      <% end %>
    </div>
  </div>
</div>